# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install Dotnet core 4.3'
  inputs:
    packageType: 'sdk'
    version: 'v4.7.2'
    includePreviewVersions: true
  enabled: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'ListSubscriptions.csproj'
    feedsToUse: 'select'
    restoreDirectory: '$(System.DefaultWorkingDirectory)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ListSubscriptions.csproj'
    arguments: '-c Release'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(Build.ArtifactStagingDirectory)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    



